# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-14 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_model', '0003_auto_20180414_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(default='男', max_length=10),
        ),
    ]
